#Credenciais do Banco de Dados
spring.datasource.url=jdbc:mysql://localhost:3306/saas_pagamentos_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=112569

#Comportamento do Hibernate
# "update" diz ao Spring para criar ou atualizar as tabelas automaticamente baseado nas suas classes @Entity
spring.jpa.hibernate.ddl-auto=update

#Mostrar as queries SQL no console do IntelliJ (útil para debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true